title: Контрольная сумма
description: Контрольная сумма - ежегодная бесплатная акция по проверке знаний школьной математики. Принять участие в акции может любой желающий.
baseurl: ""
url: "http://kontrsumma.ru"